# Generated by Django 5.2.1 on 2025-06-21 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'Address must be at least 5 characters long')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator('Enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+38 (XXX) XXX-XX-XX'. Up to 15 digits allowed.", regex='^\\+38 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
