# Generated by Django 5.2.3 on 2025-06-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_app", "0002_alter_contact_address_alter_contact_email_and_more"),
        ("contact_app", "0002_note_app_add_colornote"),
    ]

    operations = []
