# Generated by Django 5.2.3 on 2025-06-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_note_app_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
