# Generated by Django 5.2.1 on 2025-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_name', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('currency_code', 'date')},
            },
        ),
    ]
